proyecto1/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from preguntasYrespuestas.views import index, pregunta_detalle, crear_pregunta, editar_pregunta
from proyecto1 import views
admin.autodiscover()

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^response/(?P<pregunta_id>\d+)/$', pregunta_detalle, name='pregunta_detalle'),
    url(r'^response/$', index, name='preguntas'),
    url(r'^response/crear', crear_pregunta,name='crear_pregunta'),
    url(r'^response/editar/(?P<pregunta_id>\d+)/$', editar_pregunta,name='editar_pregunta'),
    url(r'^login/$', views.login_page, name='Login'),
    url(r'^logout/$', views.exit, name='Logout'),
    url(r'^$', views.home, name='home')
]

preguntasYrespuestas/models.py
from django.db import models
from django.utils import timezone

class Pregunta(models.Model):
	asunto = models.CharField(max_length=200)
	descripcion = models.TextField()
	fecha_publicacion = models.DateTimeField(auto_now_add=True)

	def _str_(self):
		return self.asunto

	def publicado_hoy(self):
		return self.fecha_publicacion.date() == timezone.now().date()
	publicado_hoy.boolean = True
	publicado_hoy.short_description = '¿Preguntado Hoy?'
		
class Respuesta(models.Model):
	Pregunta = models.ForeignKey(Pregunta)
	contenido = models.TextField()
	mejor_respuesta = models.BooleanField('Respuesta preferida', default = False)

	def __str__(self):
		return self.contenido

proyecto1/forms.py
from django import forms

class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

preguntasYrespuestas/views.py
from django.http import HttpResponse, Http404
from preguntasYrespuestas.models import Pregunta,Respuesta
from django.shortcuts import  get_object_or_404, render_to_response, redirect, render
from  django.contrib.auth.decorators import login_required
from  preguntasYrespuestas.form import PreguntaForm,RespuestaForm
from django.utils import timezone


def index(request):
    preguntas = Pregunta.objects.all()
    return render_to_response('preguntasYrespuestas/index.html',{'preguntas':preguntas})

def pregunta_detalle(request, pregunta_id):
    form = RespuestaForm()
    pregunta = get_object_or_404(Pregunta, pk=pregunta_id)
    if request.method == 'POST':
        respuesta = request.POST.get('contenido')
        pregunta.respuesta_set.create(contenido=respuesta)
        pregunta.save()
    return render(request, 'preguntasYrespuestas/pregunta_detalle.html',{'pregunta':pregunta,'form':form})

@login_required
def crear_pregunta(request):
    if request.method == 'POST':
        form = PreguntaForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('preguntas')
    else:
        form = PreguntaForm()
    return render(request,'preguntasYrespuestas/crear_pregunta.html',{'form':form})

@login_required
def editar_pregunta(request, pregunta_id):
    pregunta = get_object_or_404(Pregunta, pk=pregunta_id)
    if request.method == 'POST':
        form = PreguntaForm(request.POST, instance=pregunta)
        if form.is_valid():
            form.save()
            return redirect('pregunta_detalle',pregunta_id)
    else:
        form = PreguntaForm(instance=pregunta)
    return render(request,'preguntasYrespuestas/editar_pregunta.html',{'form':form})

proyecto1/views.py
from django.shortcuts import render, redirect
from proyecto1.forms import LoginForm
from django.contrib.auth import authenticate, login, logout

def login_page(request):
    message = None
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = authenticate(username=username, password=password)
            if user is not None:
                if user.is_active:
                    login(request,user)
                    return redirect('home')
            else:
                message = 'Inactivo'
        else:
            message = 'Datos incorrectos'
    else:
        form = LoginForm()
    return render(request,'login.html',{'message':message,'form':form})

def home(request):
    return render(request,'home.html',{})

def exit(request):
    logout(request)
    return redirect('home')

preguntasYrespuestas/templates/home.html
{% extends 'kernel.html' %}
{% block content %}
    <h3>Bienvenido, Pagina de inicio</h3>
    <a href="{% url 'preguntas' %}" class="btn waves-effect waves-light  green darken-2">Ver Preguntas</a>
{% endblock %}

preguntasYrespuestas/templates/kernel.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
	<script src="{% static 'js/jquery.js' %}"></script>
	 <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
	 <link rel="stylesheet" type="text/css" href="{%  static 'css/materialize.css' %}">
	 <link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}">
	<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet"> <link rel="shortcut icon" href="http://mispass.tk/panel.php/include/icon.png">
</head>
<body>
    <header>
   	    <nav>
              <a href="#" class="brand-logo center">Encuestas</a>
            <ul>
                  <li><li><a href="{% url 'home' %}"><i class="material-icons left">home</i></a> </li></li>
                  <li><a href="{% url 'preguntas' %}">Preguntas</a></li>
                  <li><a href="{% url 'crear_pregunta' %}">Agregar</a></li>
            </ul>
        </nav>
    </header>
     <div id="header" class="card">
        <div class="card purple  lighten-5">
             <span class="card-title" ><h2 class="center">Preguntas y respuestas</h2></span>
        </div>
        {% if user.is_authenticated %}
            <p>Bienvenido. Se ha iniciado sesion con el usuario <b>{{ user.username }} , <a href="{% url 'Logout' %}">cerrar session</a></b></p>
        {% else %}
            <p>Bienvenido. Si es adminitrador puede <a href="{% url 'Login' %}">Iniciar Sesion</a> y añadir nuevas preguntas!</p>
        {% endif %}
    </div>

    <div id="content">
        {% block content %}{% endblock %}
    </div>

</body>
</html>

preguntasYrespuestas/templates/login.html
{% extends 'kernel.html' %}
{% block content %}
    {% if message %}
        <b>{{ message }}</b>
    {% endif %}
    <div class="container formulario" id="logear">
      <div class="card bordered z-depth-2" style="margin:0% auto; max-width:400px;" >
        <div class="card-header">
           <i class="material-icons medium white-text">perm_identity</i>
        </div>
        <div class="card-content">
          <form action="" method="POST">{% csrf_token %}
            {% for field in form %}
                <div class="input-field col s12">
                    {{ field.errors }}
                    {{ field.label_tag }} <br>
                    {{ field }}
                </div>
            {% endfor %}
              <input type="submit"  value="Iniciar" class="waves-effect waves-light btn blue darken-4 right"><i class="material-icons left white-text">perm_identity</i></button>
              <br>
          </form>
        </div>
      </div>
    </div>
{% endblock %}

preguntasYrespuestas/templates/preguntasYrespuestas/crear_pregunta.html
{% extends 'kernel.html' %}
{% block content %}
    <form action="" method="POST" class="container">{% csrf_token %}
        {% include 'preguntasYrespuestas/form_pregunta.html' %}
        <input type="submit" value="Guardar" class="waves-effect waves-light btn-large blue darken-4">
         <a href="{% url 'preguntas' %}" class="btn waves-effect waves-light btn-large green darken-2">Ir a Preguntas</a>
    </form>
{% endblock %}

preguntasYrespuestas/templates/preguntasYrespuestas/editar_pregunta.html
{% extends 'kernel.html' %}
{% block content %}
    <form action="" method="POST" class="container">{% csrf_token %}
        {% include 'preguntasYrespuestas/form_pregunta.html' %}
        <input type="submit" value="Modificar" class="waves-effect waves-light btn-large blue darken-4">
        <a href="{% url 'preguntas' %}" class="btn waves-effect waves-light btn-large  green darken-2">Ir a Preguntas</a>
    </form>
{% endblock %}

preguntasYrespuestas/templates/preguntasYrespuestas/form_pregunta.html
<div class="card">
    <div class="card">
      <span class="card-title" ><h4 >Añadir Pregunta</h4></span>
    </div>
    {% for field in form %}
                <div class="input-field col s6">
                    {{ field.errors }}
                    {{ field.label_tag }} <br>
                    {{ field }}
                </div>
    {% endfor %}
</div>

preguntasYrespuestas/templates/preguntasYrespuestas/index.html
{% extends 'kernel.html' %}{
{% block content %}
    <div class="container">
        <table class='striped card' border='2' id='tblTabla' width='100%'>
            <h6>PREGUNTAS REGISTRADAS</h6>
            <thead><th>PREGUNTA</th><th>ACCION</th></thead>
            <tbody>
            {% for pregunta in preguntas %}
                <tr style='display: table-row;'>
                <td><a href="{% url "pregunta_detalle" pregunta.id %}">{{ pregunta.asunto }} ?</a> <br></td>
                <td>
                    <a href="{% url "pregunta_detalle" pregunta.id  %}" class="btn waves-effect waves-lightgreen darken-2">Ver Detalles</a>
                    <a href="{% url "editar_pregunta" pregunta.id %} " class="btn waves-effect waves-light blue darken-4"> Modificar</a>
                </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        <div class="row">
            <div class="col ">
                <a href="{% url "crear_pregunta"%} " class="btn waves-effect waves-light  green darken-2"> Añadir Nueva</a>
            </div>
         </div>
    </div>
{% endblock %}

preguntasYrespuestas/templates/preguntasYrespuestas/pregunta_detalle.html
{% extends 'kernel.html' %}
{% block content %}
    <div class="container">
        <div class="row">
        <div class="col ">
          <div class="card">
            <div class="card">
              <span class="card-title" ><h2 >{{ pregunta.asunto }}</h2></span>
            </div>
            <div class="card-content">
            <p><b>Publicado: </b>{{ pregunta.fecha_publicacion }}</p>
                <h4>Descripcion</h4>
                <p>
                    {% if pregunta.descripcion %}
                        {{ pregunta.descripcion }}
                    {% else %}
                        No hay descripcion
                    {% endif %}
                </p>
                <h4>Respuestas</h4>
                <ul>
                    {% for respuesta in pregunta.respuesta_set.all %}
                        <li>{{ respuesta.contenido}}</li>
                        <hr>
                    {% empty %}
                        <li> Aun no hay respuestas</li>
                    {% endfor %}
                </ul>
            </div>
          </div>
          <br>
          <div>
               <div class="card">
                <div class="card">
                <span class="card-title" ><h5 >Añadir Respuesta</h5></span>
                </div>
                  <div class="card-content">
                     <label for="id_contenido">Enviar Respuesta</label>
                      <form method="POST">{% csrf_token %}
                          {% for field in form %}
                                <div class="input-field col s6">
                                    {{ field }}
                                </div>
                          {% endfor %}
                          <input type="submit" value="Responder" class="waves-effect waves-light btn teal center"></button>
                      </form>
                  </div>
            </div>
          </div>
        </div>
      </div>
         <div class="row">
            <div class="col ">
                <a href="{% url "editar_pregunta" pregunta.id %} " class="btn waves-effect waves-light blue darken-4"> Modificar</a>
                <a href="{% url 'preguntas' %}" class="btn waves-effect waves-light green darken-2">Ir a Preguntas</a>
            </div>
         </div>
    </div>
{% endblock %}